# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno"
  namespace: "sno"
spec:
  # The base domain used by our SNOs
  baseDomain: "lmf.openshift.es"
    # The secret name of the secret containing the pull secret for our disconnected registry
  pullSecretRef:
    name: "disconnected-registry-pull-secret"
    # The OCP release we will be deploying otherwise specified (this can be configured per cluster as well)
  clusterImageSetNameRef: "img4.12.0-x86-64-appsub"
  # The OCP release we will be deploying otherwise specified (this can be configured per cluster as well)
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCIwy1xjLDgiUIPtYEoI9fn0/Vy9m1atkjGHXURZd+gjLYzgqP8gyUFjtRLkZsPSGmi4m7dBT/DH+Es1NnHKqY9xfDtScayt7B0v6T1W16jcZim6EDFQOHKfo1K7wYlgrd2OteIxUGRVsQ/rjg5ZFvPUsdyVk1yTTvkNzcdhk6XPtScUjIFOaB/ncFh/Gj2xhx05QyHaqbqNuPGsSoO6IbjyojtLAZQYDXRkeksVRrmLdaTh+P7TbaEamRO6ncLV1nlLXt9cjPPWQDbDqpr5O7bJG2MdFA5g4o66mbkm7siGcEsUdg0xn4darcapTHKHQa7EOg9lgID/9cE/QcKPxwCFlQ70mcPFsMsoGHB0jUcoz3wsj3/2Mw326T9EeJE3sUnRojgpLGGLrnAn8tcyZOVx5Vy1GuW2rXqW+x4HpulTOZbDv+ZoUPy0xt4dUM1R4M/9Wvq+SKVsgZXvkUPGthUzleqWEOrdaOQO8RFrWZx4JzKtGBj6NGzntjegU+sykk= luferrar@x1-lmf"
  clusters:
  - clusterName: "sno"
    # The sdn plugin that will be used
    networkType: "OVNKubernetes"
    # installConfigOverrides is a generic way of passing install-config
    # parameters through the siteConfig.  The 'capabilities' field configures
    # the composable openshift feature.  In this 'capabilities' setting, we
    # remove all but the marketplace component from the optional set of
    # components.
    #installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\" ] }}"
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      vendor: OpenShift
      #feature.open-cluster-management.io/addon-search-collector: available
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
      #group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "sno"
        # Pod's SDN network range
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    machineNetwork:
      - cidr: "10.16.16.0/24"
    # Services SDN network range
    serviceNetwork:
      - "172.30.0.0/16"
    #additionalNTPSources:
    #  - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "onlogic.lmf.openshift.es"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia://192.168.1.199:8000/redfish/v1/Systems/66506222-765b-4933-846e-1c8ede1c3291"
                  # The secret name of the secret containing the bmc credentials for our bare metal node
        bmcCredentialsName:
          name: "bmc-ztp-secret-1"
                    # The MAC Address of the NIC from the bare metal node connected to the machineNetwork
        bmcDisableCertificateVerification: true
        bootMACAddress: "84:8b:cd:4d:15:d2"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        #rootDeviceHints:
        #  wwn: "0x11111000000asd123"
        # example of diskPartition below is used for image registry (check ImageRegistry.md for more details), but it's not limited to this use case
#        diskPartition:
#          - device: /dev/disk/by-id/wwn-0x11111000000asd123 # match rootDeviceHints
#            partitions:
#              - mount_point: /var/imageregistry
#                size: 102500
#                start: 344844
#cpuset: "0-1,20-21" # match the value with PerformanceProfile's .spec.cpu.reserved for workload partitioning. See /example/policygentemplates/group-du-sno-ranGen.yaml
        nodeNetwork:
          interfaces:
            - macAddress: '52:54:00:1f:f5:17'
              name: eth0
          config:
            interfaces:
              - ipv4:
                  address:
                    - ip: 192.168.1.199
                      prefix-length: 24
                  dhcp: false
                  enabled: true
                macAddress: '52:54:00:1f:f5:17'
                name: eth0
                state: up
                type: ethernet
            dns-resolver:
              config:
                server:
                  - 192.168.1.1
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-address: 192.168.1.1
                  next-hop-interface: eth0
                  table-id: 254
